"""Overview dashboard view."""

import pandas as pd
import plotly.express as px
from views.shared import (
    _layout,
    _sidebar,
    _fig_div,
    _fmt_percent,
    _fmt_number,
    _to_float,
    _safe_text,
    page_card_grid,
    TICKER_NAMES
)

def page_overview(summary: pd.DataFrame, recommendations: pd.DataFrame, sectors: pd.DataFrame, rec_dist: pd.DataFrame, risk_return_fig) -> str:
    hero_stats = []
    if not summary.empty:
        r = summary.iloc[0]
        hero_stats = [
            ("Market coverage", f"{int(_to_float(r.get('total_stocks'))):,}", "Stocks included in the current universe", "#1f77b4"),
            ("Positive bias", f"{int(_to_float(r.get('buy_count'))):,}", "BUY signals generated by the model", "#2ca02c"),
            ("Neutral stance", f"{int(_to_float(r.get('hold_count'))):,}", "HOLD signals suggesting watchlist candidates", "#ff7f0e"),
            ("Average return", _fmt_percent(r.get('avg_predicted_return')), "Mean predicted upside across the universe", "#5d7085"),
        ]

    buy_rows = recommendations[recommendations['Recommendation'] == 'BUY'].head(5) if not recommendations.empty else pd.DataFrame()
    avoid_rows = recommendations[recommendations['Recommendation'] == 'AVOID'] if not recommendations.empty else pd.DataFrame()
    
    top_buy = ""
    for _, row in buy_rows.iterrows():
        ticker_val = _safe_text(row['Ticker'])
        name_val = TICKER_NAMES.get(ticker_val, ticker_val)
        top_buy += f"""
          <div class='signal-card signal-buy'>
            <h4>{ticker_val} <span class='muted'>({name_val})</span> <span class='pill pill-buy ms-2'>BUY</span></h4>
            <div class='signal-row'><span>Predicted return</span><strong>{_fmt_percent(row['Predicted_Return'])}</strong></div>
            <div class='signal-row'><span>Confidence</span><strong>{_fmt_number(row['Confidence_Score'], 0, suffix='/10')}</strong></div>
            <div class='signal-row'><span>Volatility</span><strong>{_to_float(row.get('Volatility'))/100:.4f}</strong></div>
            <div class='signal-row'><span>Risk</span><strong>{_safe_text(row['Risk_Level'])}</strong></div>
          </div>
        """
    if not top_buy:
        top_buy = "<div class='empty-state'>No BUY recommendations available.</div>"

    top_avoid = ""
    for _, row in avoid_rows.iterrows():
        ticker_val = _safe_text(row['Ticker'])
        name_val = TICKER_NAMES.get(ticker_val, ticker_val)
        top_avoid += f"""
          <div class='signal-card signal-avoid'>
            <h4>{ticker_val} <span class='muted'>({name_val})</span> <span class='pill pill-avoid ms-2'>AVOID</span></h4>
            <div class='signal-row'><span>Predicted return</span><strong>{_fmt_percent(row['Predicted_Return'])}</strong></div>
            <div class='signal-row'><span>Confidence</span><strong>{_fmt_number(row['Confidence_Score'], 0, suffix='/10')}</strong></div>
            <div class='signal-row'><span>Volatility</span><strong>{_to_float(row.get('Volatility'))/100:.4f}</strong></div>
            <div class='signal-row'><span>Risk</span><strong>{_safe_text(row['Risk_Level'])}</strong></div>
          </div>
        """
    if not top_avoid:
        top_avoid = "<div class='empty-state'>No AVOID recommendations available.</div>"

    charts_html = ""
    if rec_dist is not None and not rec_dist.empty:
        fig = px.pie(
            rec_dist, 
            values='count', 
            names='Recommendation', 
            title='Recommendation Distribution', 
            hole=0.35,
            color='Recommendation',
            color_discrete_map={'BUY': '#2ca02c', 'HOLD': '#ff7f0e', 'AVOID': '#d62728'}
        )
        charts_html += "<div class='card-shell mb-3'><h3 class='section-title mt-0'>Signal Distribution</h3>" + _fig_div(fig, 'overview_rec_dist') + "</div>"

    return _layout(
        "Investment Advisor Dashboard",
        "A polished market snapshot with recommendation signals, sector view, and risk-return positioning, designed as a Bootstrap dashboard.",
        f"""
        {page_card_grid(hero_stats)}
        <div class='card-shell mb-4'>
          <strong>How to read this dashboard:</strong> BUY cards point to stronger return setups, AVOID cards flag higher risk or weaker setups, and the charts summarize how the model is distributing those signals across sectors and risk bands.
        </div>
        
        <div class='row mb-4'>
          <div class='col-lg-6'>
            <div class='section-title mt-0'>Top BUY Recommendations</div>
            {top_buy}
          </div>
          <div class='col-lg-6'>
            <div class='section-title mt-0'>Stocks to AVOID</div>
            {top_avoid}
          </div>
        </div>

        <div class='row mb-4'>
          <div class='col-lg-5'>
            <div class='section-title mt-0'>Model Overview</div>
            {charts_html}
          </div>
          <div class='col-lg-7'>
            <div class='section-title mt-0'>Investment Strategy Context</div>
            <div class='card-shell height-100'>
              <div class='row g-3'>
                <div class='col-md-12'>
                  <div class='p-3 border rounded mb-2' style='border-left:4px solid #2ca02c !important;'>
                    <strong class='text-success'>BUY Signals</strong>
                    <p class='small text-muted mt-1 mb-0'>Strong predicted upward momentum over the weekly (5-day) horizon. Portfolio strategy: Accumulate or overweight positions to capture short-term capital appreciation.</p>
                  </div>
                </div>
                <div class='col-md-12'>
                  <div class='p-3 border rounded mb-2' style='border-left:4px solid #ff7f0e !important;'>
                    <strong class='text-warning'>HOLD Signals</strong>
                    <p class='small text-muted mt-1 mb-0'>Neutral outlook with minor price fluctuations. Portfolio strategy: Maintain current exposure, monitor moving averages, or prioritize for yield/income stability.</p>
                  </div>
                </div>
                <div class='col-md-12'>
                  <div class='p-3 border rounded' style='border-left:4px solid #d62728 !important;'>
                    <strong class='text-danger'>AVOID Signals</strong>
                    <p class='small text-muted mt-1 mb-0'>Downside momentum or elevated risk profile. Portfolio strategy: Exit positions, reallocate capital, or utilize hedging instruments to reduce exposure.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class='section-title'>Market Universe & Sector Profile</div>
        <div class='card-shell mb-4'>
          <p>The recommendation engine tracks a diversified universe of <strong>10 major blue-chip equities</strong> representing critical sectors of the S&P 500 index. These selections provide high-liquidity coverage across distinct industry profiles:</p>
          <div class='row g-3 mt-1'>
            <div class='col-md-6 col-lg-4'>
              <div class='p-3 border rounded height-100 bg-light'>
                <strong style='color:#1f77b4;'>Technology</strong>
                <ul class='small text-muted mb-0 ps-3 mt-2'>
                  <li><strong>AAPL:</strong> Apple Inc. (Consumer Electronics)</li>
                  <li><strong>MSFT:</strong> Microsoft Corp. (Software & Cloud)</li>
                  <li><strong>GOOGL:</strong> Alphabet Inc. (Search & Ads Services)</li>
                  <li><strong>META:</strong> Meta Platforms Inc. (Social Media & Ads)</li>
                  <li><strong>NVDA:</strong> NVIDIA Corp. (Semiconductors & AI Hardware)</li>
                </ul>
              </div>
            </div>
            <div class='col-md-6 col-lg-4'>
              <div class='p-3 border rounded height-100 bg-light'>
                <strong style='color:#2ca02c;'>Consumer & Retail</strong>
                <ul class='small text-muted mb-0 ps-3 mt-2'>
                  <li><strong>AMZN:</strong> Amazon.com Inc. (E-Commerce & Cloud)</li>
                  <li><strong>WMT:</strong> Walmart Inc. (Mass Market Retail)</li>
                </ul>
              </div>
            </div>
            <div class='col-md-6 col-lg-4'>
              <div class='p-3 border rounded height-100 bg-light'>
                <strong style='color:#ff7f0e;'>Cyclical & Services</strong>
                <ul class='small text-muted mb-0 ps-3 mt-2'>
                  <li><strong>TSLA:</strong> Tesla Inc. (Electric Automobiles)</li>
                  <li><strong>NFLX:</strong> Netflix Inc. (Streaming Entertainment)</li>
                  <li><strong>JPM:</strong> JPMorgan Chase & Co. (Diversified Financials)</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        """,
        _sidebar("Overview"),
    )
