"""Overview page."""

import streamlit as st

from components import charts, metrics
from data import queries
from dashboard_pages.shared import render_hero, render_metric_card, render_recommendation_card, to_float
from formatters import safe_percent_format


def show_overview():
    render_hero(
        "Investment Advisor Dashboard",
        "A structured market snapshot with recommendations, risk signals, and model-backed analytics. Use this view to understand the current market stance at a glance.",
        eyebrow="AI-Powered Portfolio Intelligence",
    )

    summary = queries.get_recommendation_summary()
    recommendations = queries.get_recommendations()
    sectors = queries.get_sector_analysis()
    rec_dist = queries.get_recommendation_distribution()
    risk_return = queries.get_risk_return_data()

    metrics.display_kpi_cards(summary)

    if not summary.empty:
        summary_row = summary.iloc[0]
        total_stocks = to_float(summary_row.get('total_stocks'))
        buy_count = to_float(summary_row.get('buy_count'))
        hold_count = to_float(summary_row.get('hold_count'))
        avg_return = to_float(summary_row.get('avg_predicted_return'))

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            render_metric_card("Market coverage", f"{int(total_stocks):,}", "Stocks included in the current recommendation set", accent="blue")
        with col2:
            render_metric_card("Positive bias", f"{int(buy_count):,}", "BUY signals generated by the model", accent="green")
        with col3:
            render_metric_card("Neutral stance", f"{int(hold_count):,}", "HOLD signals suggesting watchlist candidates", accent="orange")
        with col4:
            render_metric_card("Average return", safe_percent_format(avg_return), "Mean predicted upside across the universe", accent="slate")

    st.markdown(
        """
        <div class="callout-box">
            <strong>How to read this dashboard:</strong> BUY cards point to stronger return setups, AVOID cards flag higher risk or weaker setups, and the charts below summarize how the model is distributing those signals across sectors and risk bands.
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown('<div class="section-header">Top Investment Opportunities</div>', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("🟢 Top BUY Recommendations")
        buy_recs = recommendations[recommendations['Recommendation'] == 'BUY'].head(5)
        if not buy_recs.empty:
            for _, row in buy_recs.iterrows():
                render_recommendation_card(row, tone="buy")
        else:
            st.info("No BUY recommendations available")

    with col2:
        st.subheader("🔴 Stocks to AVOID")
        avoid_recs = recommendations[recommendations['Recommendation'] == 'AVOID']
        if not avoid_recs.empty:
            for _, row in avoid_recs.iterrows():
                render_recommendation_card(row, tone="avoid")
        else:
            st.info("No AVOID recommendations")

    st.markdown('<div class="section-header">Market Analytics</div>', unsafe_allow_html=True)

    st.markdown(
        """
        <div class="callout-box">
            <strong>Context:</strong> The left chart shows signal distribution by recommendation type, the right chart shows which sectors are currently carrying the highest average predicted returns, and the scatter plot highlights the trade-off between risk and expected upside.
        </div>
        """,
        unsafe_allow_html=True,
    )

    col3, col4 = st.columns(2)

    with col3:
        if not rec_dist.empty:
            st.plotly_chart(charts.create_recommendation_pie(rec_dist), use_container_width=True)

    with col4:
        if not sectors.empty:
            st.plotly_chart(charts.create_sector_bar(sectors), use_container_width=True)

    if not risk_return.empty:
        st.plotly_chart(charts.create_risk_return_scatter(risk_return), use_container_width=True)
