"""Metric display components."""

import streamlit as st

from formatters import safe_decimal_format, safe_percent_format


def _metric_tile(label, value, subtitle="", accent="#1f77b4", delta_text=None, delta_color="#2ca02c"):
    delta_html = ""
    if delta_text:
        delta_html = f"<div class='metric-delta' style='color:{delta_color}'>{delta_text}</div>"

    st.markdown(
        f"""
        <div class="metric-card" style="border-top: 4px solid {accent}; background: rgba(255,255,255,0.98);">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
            {delta_html}
            <div class="metric-subtitle">{subtitle}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def display_kpi_cards(summary_df):
    """Display KPI metric cards."""
    if summary_df.empty:
        st.warning("No data available")
        return
    
    row = summary_df.iloc[0]
    
    col1, col2, col3, col4, col5 = st.columns(5)
    
    with col1:
        _metric_tile("Total Stocks", f"{int(row['total_stocks']):,}", "Stocks available in the current universe", accent="#1f77b4")
    
    with col2:
        _metric_tile("BUY", f"{int(row['buy_count']):,}", "Strong signals generated by the model", accent="#2ca02c", delta_text="Strong Signals", delta_color="#2ca02c")
    
    with col3:
        _metric_tile("HOLD", f"{int(row['hold_count']):,}", "Neutral setups to monitor", accent="#ff7f0e")
    
    with col4:
        _metric_tile("AVOID", f"{int(row['avoid_count']):,}", "Higher-risk names flagged by the model", accent="#d62728", delta_text="Caution", delta_color="#d62728")
    
    with col5:
        avg_return = row['avg_predicted_return']
        try:
            avg_return_float = float(avg_return)
            _metric_tile(
                "Avg Predicted Return",
                safe_percent_format(avg_return),
                "Mean upside across all stocks",
                accent="#5d7085",
                delta_text=safe_percent_format(avg_return),
                delta_color="#2ca02c" if avg_return_float > 0 else "#d62728",
            )
        except (ValueError, TypeError):
            _metric_tile("Avg Predicted Return", "N/A", "Mean upside across all stocks", accent="#5d7085")


def display_stock_metrics(stock_df):
    """Display metrics for a specific stock."""
    if stock_df.empty:
        st.warning("No data available for this stock")
        return
    
    row = stock_df.iloc[0]
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        _metric_tile("Current Price", safe_decimal_format(row['Close'], prefix='$'), "Latest close price", accent="#1f77b4")
    
    with col2:
        pred_return = row['Predicted_Return']
        try:
            pred_return_float = float(pred_return)
            _metric_tile(
                "Predicted Return",
                safe_percent_format(pred_return),
                "Model-estimated upside",
                accent="#2ca02c" if pred_return_float > 0 else "#d62728",
                delta_text=safe_percent_format(pred_return),
                delta_color="#2ca02c" if pred_return_float > 0 else "#d62728",
            )
        except (ValueError, TypeError):
            _metric_tile("Predicted Return", "N/A", "Model-estimated upside", accent="#5d7085")
    
    with col3:
        _metric_tile("Confidence Score", safe_decimal_format(row['Confidence_Score'], decimals=0, suffix='/10'), "Model confidence on this signal", accent="#ff7f0e")
    
    # Second row
    col4, col5, col6 = st.columns(3)
    
    with col4:
        # Recommendation with color
        rec = row['Recommendation']
        color = '#2ca02c' if rec == 'BUY' else '#ff7f0e' if rec == 'HOLD' else '#d62728'
        st.markdown(f"**Recommendation:** <span style='color:{color}; font-size:20px; font-weight:bold'>{rec}</span>", unsafe_allow_html=True)
    
    with col5:
        # Risk level with color
        risk = row['Risk_Level']
        risk_color = '#2ca02c' if risk == 'LOW' else '#ff7f0e' if risk == 'MEDIUM' else '#d62728'
        st.markdown(f"**Risk Level:** <span style='color:{risk_color}; font-weight:bold'>{risk}</span>", unsafe_allow_html=True)
    
    with col6:
        st.markdown(f"**Sector:** {row['Sector']}")
    
    # Explanation
    st.info(f"**Analysis:** {row['Explanation']}")


def format_recommendation(rec):
    """Format recommendation with color."""
    color = '#2ca02c' if rec == 'BUY' else '#ff7f0e' if rec == 'HOLD' else '#d62728'
    return f"<span style='color:{color}; font-weight:bold'>{rec}</span>"


def format_risk(risk):
    """Format risk level with color."""
    color = '#2ca02c' if risk == 'LOW' else '#ff7f0e' if risk == 'MEDIUM' else '#d62728'
    return f"<span style='color:{color}'>{risk}</span>"